menu:
    Index: https://luoyefe.com
    Archives: /blog/archives/
    Zhihu: https://www.zhihu.com/people/luo-ye-42-22
    Github: https://github.com/luoye-fe

favicon: /favicon.ico
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: luoye-fe

# Analytics
# google-analytics:
ga: UA-78104533-1

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
